apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: mp3
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:  # template模板来创建Pod资源
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: Never
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq  # 这个路径是用来存储queue的
              subPath: rabbitmq/data # 子路径, 相对路径
              readOnly: false
#            - name: rabbitmq-volume
#              mountPath: /etc/rabbitmq/rabbitmq.conf  # 这个路径是用来存储queue的
#              subPath: rabbitmq/conf/rabbitmq.conf # 子路径, 相对路径
#              readOnly: True
#            - name: rabbitmq-volume
#              mountPath: /etc/rabbitmq/definitions.json  # 这个路径是用来存储queue的
#              subPath: rabbitmq/conf/definitions.json # 子路径, 相对路径
#              readOnly: True
      volumes:
        - name: rabbitmq-volume
          hostPath:
            path: /root/microservices-python
            type: Directory
