apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mp3
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
    - protocol: TCP
      port: 5672
      targetPort: 5672