apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mp3
spec:
  selector:
    matchLabels:
      app: mysql
  template:  # template模板来创建Pod资源
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: Never
          ports:
            - name: http
              protocol: TCP
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql # 容器内的路径
              subPath: mysql/data # 容器内的路径
              readOnly: false
      volumes:
      - name: mysql-data
        hostPath:
          path: /root/microservices-python
          type: Directory