apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-configmap
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
              subPath: mongodb/data
              readOnly: false
      volumes:
      - name: mongo-data
        hostPath:
          path: /root/microservices-python
          type: Directory