apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mp3
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017
